---
title: "Parameter_Analysis"
author: "Jonas Bruno"
date: "2024-04-11"
output: pdf_document
---

### Load Packages
```{r setup, include=FALSE}
Sys.setLanguage("en")
library(tidyverse)
library(ggrepel)
library(nflreadr)
library(nflplotR)

library(conflicted)
library(dplyr)
library(ggplot2)
library(zoo)

conflicts_prefer(dplyr::filter)

```

### Intercept vs Slope parameter
This plot is a quick way to compare all players and their respective parameters

The function is as follows:


```{r}

kicker_comparison_plot <- function(year, parameter_data, left = 0.02, right= 0.02, up = 0.5, down = 0.5) {

slope_mean <- mean(parameter_data$slope)
intercept_mean <- mean(parameter_data$intercept)

cross_coords <- data.frame(slope_mean, intercept_mean)

ggplot(parameter_data, aes(x = slope, y = intercept)) +
  geom_point() +  # Add points
  geom_point(data = cross_coords, aes(x = slope_mean, y = intercept_mean), shape = 4, size = 4, color = "blue") +  # Add cross marker
  geom_text_repel(aes(label = full_season_data.player_name), size = 2, nudge_x = 0.0001, nudge_y = 0.0001) +  # Add names with adjusted font size
  
  geom_hline(yintercept = intercept_mean, linetype = "dotted", color = "blue") + # Add horizontal line
  geom_vline(xintercept = slope_mean, linetype = "dotted", color = "blue") + # Add vertical line
  geom_text(aes(x = slope_mean-left, y = intercept_mean-down, label = "Reliably Average"), size = 3)+
  geom_text(aes(x = slope_mean+right, y = intercept_mean-down, label = "Go for it"), size = 3)+
  geom_text(aes(x = slope_mean+right, y = intercept_mean+up, label = "Fast Regression"), size = 3)+
  geom_text(aes(x = slope_mean-left, y = intercept_mean+up, label = "Elite"), size = 3)+
  
  labs(x = "Slope", y = "Pat") +  # Label axes
  ggtitle(paste("PAT vs. FG-Slope", year)) +
  theme(
    text = element_text(size = 12),  # Adjust font size for all text elements
    axis.title = element_text(size = 12),  # Adjust font size for axis titles
    plot.title = element_text(size = 14)  # Adjust font size for plot title
  )

}

```






Now we can plot everything:

## 2023 Season
```{r}
kicker_comparison_plot(2023, result_data$"2023_Season", 0.009, 0.02, 0.77, 0.96)
```


## 2022 Season
```{r}
kicker_comparison_plot(2022, result_data$"2022_Season", 0.01, 0.01)
```

## 2021 Season
```{r}
kicker_comparison_plot(2021, result_data$"2021_Season", 0.01, 0.02, 0.7, 0.7)
```

## 2020 Season
```{r}
kicker_comparison_plot(2020, result_data$"2020_Season", 0.01, 0.02, 0.7, 0.8)
```


## 2019 Season
```{r}
kicker_comparison_plot(2019, result_data$"2019_Season", 0.01, 0.02, 0.7, 0.66)
```


## 2018 Season
```{r}
kicker_comparison_plot(2018, result_data$"2018_Season", 0.01, 0.015, 0.5, 0.4)
```


## 2017 Season
```{r}
kicker_comparison_plot(2017, result_data$"2017_Season", 0.012, 0.02, 0.6, 0.6)
```


## 2016 Season
```{r}
kicker_comparison_plot(2016, result_data$"2016_Season", 0.02, 0.03, 0.5, 0.6)
```





