---
title: "Chris_Boswell_Analysis"
author: "Jonas Bruno"
date: "2024-04-11"
output: html_document
---

```{r}
#Extract Boswells Data over all seasons. This is a partial loop
player_parameters <- function(data, name) {
  results <- list()
  
  for (i in 1:length(data)) {
    
    extracted_season <- as.data.frame(result_data[i])
    extracted_player_season <- extracted_season[apply(extracted_season, 1, function(row) any(row == name)), ]
    
     
    results<- c(results, list(t(extracted_player_season)))
    
  }

  return(results)
}


```




```{r}
x <- player_parameters(result_data, "C.Boswell")

seasons <- c(2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023)

names(x) <- seasons
na.omit(x)
```


```{r}	


data23 <- load_pbp(2023)

data23 <- calculate_player_stats_kicking(data23)

data23_clean <- season_data(data23)

#We access, the field goal data of Pittsburgh Steelers Kicker Chris Boswell
c_boswell <- player_season(data23_clean, 5)

c_boswell <- as.data.frame(c_boswell[, -1])

c_boswell <- t(c_boswell)

parameters <- result_data$"2023_Season"

c_boswell_parameters <- parameters[5,]

colnames(c_boswell_parameters) <- c("player_name", "intercept", "slope")

#Function to show the regression
logistic_function <- function(x, intercept, slope) {
  plogis(intercept + 33 * slope - slope * x)
}

#X-axis
x_values <- seq(0, 70, 0.1)

#Y-Axis show the probabilities for success / faliure
y_values <- logistic_function(x_values, c_boswell_parameters$intercept, c_boswell_parameters$slope)

line_data <- data.frame(x_values, y_values)

ggplot(c_boswell, aes(x = first_line, y = second_line)) +
  geom_point() +
  geom_line(data = line_data, aes(x = x_values, y = y_values))+
  labs(title = "Chris Boswell (Pit) 2023 Season",
       x = "Distance",
       y = "Probability",
       caption = paste("Intercept:",
                       round(c_boswell_parameters$intercept, 2),
                      "Slope:", round(c_boswell_parameters$slope, 4))
                        
       )


```


Lets look at his 2018 Season in comparison

```{r}


data18 <- load_pbp(2018)

data18 <- calculate_player_stats_kicking(data18)

data18_clean <- season_data(data18)

#We access, the field goal data of Pittsburgh Steelers Kicker Chris Boswell
c_boswell <- player_season(data18_clean, 5)

c_boswell <- as.data.frame(c_boswell[, -1])

c_boswell <- t(c_boswell)

parameters <- result_data$"2018_Season"

c_boswell_parameters <- parameters[5,]

colnames(c_boswell_parameters) <- c("player_name", "intercept", "slope")

#Function to show the regression
logistic_function <- function(x, intercept, slope) {
  plogis(intercept + 33 * slope - slope * x)
}

#X-axis
x_values <- seq(0, 70, 0.1)

#Y-Axis show the probabilities for success / faliure
y_values <- logistic_function(x_values, c_boswell_parameters$intercept, c_boswell_parameters$slope)

line_data <- data.frame(x_values, y_values)

ggplot(c_boswell, aes(x = first_line, y = second_line)) +
  geom_point() +
  geom_line(data = line_data, aes(x = x_values, y = y_values))+
  labs(title = "Chris Boswell (Pit) 2023 Season",
       x = "Distance",
       y = "Probability",
       caption = paste("Intercept:",
                       round(c_boswell_parameters$intercept, 2),
                      "Slope:", round(c_boswell_parameters$slope, 4))
                        
       )

```
